In [16]:
import json
from pathlib import Path
import requests
import base64
from io import BytesIO
from PIL import Image

# -----------------------
# CONFIG
# -----------------------
SERVER_URL = "http://localhost:8000/pose"
IMAGE_PATH = "pose_01.jpg"          # path to a local image
JSON_PATH = "pose_01.json"

def load_meta(meta_path: Path) -> dict:
    return json.loads(meta_path.read_text(encoding="utf-8"))

# -----------------------
# SEND REQUEST
# -----------------------
with open(IMAGE_PATH, "rb") as f:
    files = {
        "image": ("test.jpg", f, "image/jpeg"),
    }
    data = {
        "payload": json.dumps(load_meta(Path(JSON_PATH)))
    }

    print("[CLIENT] Sending request...")
    resp = requests.post(SERVER_URL, files=files, data=data, timeout=120)

if resp.status_code != 200:
    print("[CLIENT] Request failed!")
    print(resp.status_code, resp.text)
    raise SystemExit(1)

result = resp.json()
print("[CLIENT] Response keys:", result.keys())
# print("[CLIENT] Num instances:", result["returned"])


[CLIENT] Sending request...
[CLIENT] Response keys: dict_keys(['ok', 'img_png'])


In [17]:
image_bytes = base64.b64decode(result['img_png'])
image = Image.open(BytesIO(image_bytes))
image.show()

In [1]:
import numpy as np
poses = np.random.rand(3, 8, 2)

In [2]:
poses

array([[[0.03513399, 0.41899426],
        [0.88365383, 0.33733072],
        [0.76564602, 0.49036467],
        [0.17407229, 0.98934968],
        [0.27764539, 0.57331684],
        [0.69036701, 0.75624615],
        [0.03853927, 0.49306392],
        [0.19435692, 0.15163637]],

       [[0.96476794, 0.73990337],
        [0.14854201, 0.25087373],
        [0.91889589, 0.36180994],
        [0.82741296, 0.46368212],
        [0.98948067, 0.97917548],
        [0.16609279, 0.9540927 ],
        [0.85401184, 0.66258935],
        [0.53099695, 0.88984407]],

       [[0.41528123, 0.53434615],
        [0.61245301, 0.42948322],
        [0.92598145, 0.32541586],
        [0.25447616, 0.19376211],
        [0.31282956, 0.01428307],
        [0.93609267, 0.83887719],
        [0.79816207, 0.29973586],
        [0.12551211, 0.06298126]]])

In [11]:
for pose in poses:
    print(pose)

[[0.03513399 0.41899426]
 [0.88365383 0.33733072]
 [0.76564602 0.49036467]
 [0.17407229 0.98934968]
 [0.27764539 0.57331684]
 [0.69036701 0.75624615]
 [0.03853927 0.49306392]
 [0.19435692 0.15163637]]
[[0.96476794 0.73990337]
 [0.14854201 0.25087373]
 [0.91889589 0.36180994]
 [0.82741296 0.46368212]
 [0.98948067 0.97917548]
 [0.16609279 0.9540927 ]
 [0.85401184 0.66258935]
 [0.53099695 0.88984407]]
[[0.41528123 0.53434615]
 [0.61245301 0.42948322]
 [0.92598145 0.32541586]
 [0.25447616 0.19376211]
 [0.31282956 0.01428307]
 [0.93609267 0.83887719]
 [0.79816207 0.29973586]
 [0.12551211 0.06298126]]
